version: "3.7"

services:
  app-dothings:
    image: docker.cloudiolab.com/cloudiolab/dothings:1.0
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
    secrets:
      - app_db_user
      - app_db_pass
      - api_secret_key
    configs:
      - source: app-entrypoint-07081854
        target: /docker-entrypoint/entrypoint.sh
    command: ["/bin/sh", "/docker-entrypoint/entrypoint.sh"]
    networks:
      - cloudiolab_common_network
    depends_on:
      - mongodb
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == jarvis]

  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_pass
      MONGO_INITDB_DATABASE: dothingsdb
    secrets:
      - mongo_root_user
      - mongo_root_pass
      - app_db_user
      - app_db_pass
    volumes:
      - mongo_db:/data/db
    configs:
      - source: mongodb-entrypoint-07081854
        target: /docker-entrypoint-initdb.d/entrypoint.sh
    command: mongod
    networks:
      - cloudiolab_common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == jarvis]

networks:
  cloudiolab_common_network:
    external: true

volumes:
  mongo_db:

secrets:
  app_db_user:
    file: ./secrets/app/app_db_user
  app_db_pass:
    file: ./secrets/app/app_db_pass
  api_secret_key:
    file: ./secrets/app/api_secret_key
  mongo_root_user:
    file: ./secrets/mongo/mongo_root_user
  mongo_root_pass:
    file: ./secrets/mongo/mongo_root_pass

configs:
  app-entrypoint-07081854:
    file: ./secrets/app/entrypoint.sh
  mongodb-entrypoint-07081854:
    file: ./secrets/mongo/entrypoint.sh
